services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: johann21
      MYSQL_DATABASE: tarea2
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/schemas.sql:/docker-entrypoint-initdb.d/schemas.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./src:/app/src           # Monta el código fuente para desarrollo
      - ./pom.xml:/app/pom.xml   # Monta el archivo pom.xml
      - maven-repo:/root/.m2     # Caché de dependencias Maven
    networks:
      - spring-network
    environment:
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      # Permitir la recarga en tiempo real
      SPRING_DEVTOOLS_REMOTE_SECRET: "mysecret"

volumes:
  mysql-data:
  maven-repo:

networks:
  spring-network:
    driver: bridge