services:
  mysql:
    image: mysql:9.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: johann21
      MYSQL_DATABASE: tarea2
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pjohann21"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring-network

  backend:
    build:
      context: .
      dockerfile: backend/dockerfile
    container_name: spring-backends
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "35729:35729" # Puerto para LiveReload
    volumes:
      - ./backend:/app
    networks:
      - spring-network
    environment:
      DB_URL: jdbc:mysql://mysql:3306/tarea2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: johann21
      JWT_SECRET: EsteEsUnSecretoMuySeguroParaFirmarElTokenCon256Bits!

volumes:
  mysql-data:

networks:
  spring-network:
    driver: bridge