services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: johann21
      MYSQL_DATABASE: tarea2
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/schemas.sql:/docker-entrypoint-initdb.d/schemas.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pjohann21"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring-network

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: spring-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "35729:35729" # Puerto para LiveReload
    volumes:
      - ./:/app
      - maven-repo:/root/.m2
      - /app/target
    networks:
      - spring-network
    environment:
      # Sólo necesitamos sobreescribir URL
      DB_URL: jdbc:mysql://mysql:3306/tarea2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    env_file: 
      - .env

volumes:
  mysql-data:
  maven-repo:

networks:
  spring-network:
    driver: bridge